# Generated by Django 3.1.2 on 2020-10-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='phtot',
            new_name='photo',
        ),
    ]
